trigger:
 - main

pool:
 vmImage: 'windows-latest' 

steps:
  - task: Docker@2
    displayName: 'Docker image build'
    inputs:
      containerRegistry: 'icoeregistry'
      repository: 'Test Repo'
      command: 'build'
      Dockerfile: '**/Dockerfile'

  - task: Docker@2
    displayName: ‘Docker image push’
    inputs:
      containerRegistry: ‘icoeregistry’
      repository: ‘Test Repo’
      command: ‘push’
  
